user: fred
wget_image: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-ec2-8.1.1911-20200113.3.x86_64.qcow2
iso_image: focal-server-cloudimg-amd64.img
image_size: 30G
server_ip: 192.168.100.125
admin_pass: admin  # Redis and mongo
