#cloud-config
ssh_pwauth: True
chpasswd:
  list: |
     root:terraform-libvirt-linux
  expire: False

users:
  - name: user
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC87GI7G0JKRh86m0h0FlUz8GjvtpnMx6zUw6rM4S/r0ueHvTvn6Uy/jV4SkqVuXi1a3LFVlnoYtBw4/CN3CgwAUUCTscSImhX8N06mrNUStcKnyCMXJDdEFuDwcYo/rndOLUeh1a8eiCJtoSvlLuoLRpQew3bpDu7tgIOYQUl9WUZkwsppq6OXlPtUeqQ4W9PnQPXSggYt9bVTd6BCJeeOaPHezJI7cKvyVl5P7qH64dvzLE7wG1rix43k8V8X3Lld8t60B2T7Fx2Q6j4wiV72knVVx83qdFZDX0Tqkb8SONUkNlQYlGRj191Hhvuvb1CKmzpM0RslhWTQEqR+GMW62BUq1UhJd75l/5qrCoyrJEZIv8y+QFiWGfDSTWGfv7XR+NTxUysHr18Qi1B7Ds1ntz8fUVIZAXKsjx/Jqq7iaDdGehf1qgBgwEQaMHjBfdBB8BZM/2QeC2OAbt15jQyZM5H/zjBAumr3SbGgBbkpTzqUV8sQJYw1XhtkswC3+mU=
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: wheel