ethernets:
    ${interface}:
        addresses:
        - ${ip_addr}/24
        dhcp4: false
        gateway4: ${gateway}
        match:
            macaddress: ${mac_addr}
        nameservers:
            addresses:
            - 1.1.1.1
            - 8.8.8.8
        set-name: ${interface}
version: 2