- name: download and unarchive an archive
  ansible.builtin.unarchive:
    src: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.10.2-linux-x86_64.tar.gz
    dst: /home/root
    remote_src: yes

- name: Replace auditbeat.yml with custom
  ansible.builtin.copy:
    src: ../auditbeat.yml
    dest: /home/root/auditbeat-7.10.2-linux-x86_64/auditbeat.yml
    mode: '644'
    owner: root

- name: Change the working directory to /home/root/auditbeat-7.10.2-linux-x86_64/ before executing the command
  ansible.builtin.shell: ./auditbeat -e
  args:
    chdir: /home/root/auditbeat-7.10.2-linux-x86_64/
