- name: Download and install Public Signign Key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Install https
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: Save repo to /etc/apt/sources.list.d/
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Install auditbeat
  apt:
    name: "auditbeat"
    state: present
    update_cache: yes

- name: Check auditbeat service status
  ansible.builtin.systemd:
    state: started
    name: auditbeat

- name: Enable auditbeat service
  ansible.builtin.systemd:
    name: auditbeat
    enabled: yes

- name: Replace auditbeat.yml with custom
  ansible.builtin.copy:
    src: ../auditbeat.yml
    dest: /etc/auditbeat/auditbeat.yml
    mode: '664'
