global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
      
  - job_name: checker
    metrics_path: api/v1/checker
    static_configs:
      - targets:
          - 192.168.31.129:8080
    basic_auth:
      username: 'checker'
      password: 'test'