- name: Disable all infrastructure on server
  hosts: monitoring_server
  gather_facts: true
  become: true

  tasks:
    - name: Include vars from server_vars.yml file
      include_vars:
        dir: vars/
        extensions:
          - 'yml'
      tags:
        include_vars

    - name: Get teams to delete networks
      uri:
        url: "http://192.168.100.116:8000/api/v1/services/teams/info"  #  This is test URL, change in to your production URL
        method: GET
        headers:
          Content-Type: "application/json"
      ignore_errors: true
      register: result
      tags: get_result

    - name: Destroy team networks
      virt_net:
        command: destroy
        name: "{{ item['name'] }}"
      with_items:
        - "{{ result.json.teams }}"
      tags: destroy_networks

    - name: Destroy default network
      virt_net:
        command: destroy
        name: default
      tags: destroy_networks

    - name: Remove team networks from autostart
      virt_net:
        autostart: no
        name: "{{ item['name'] }}"
      tags: destroy_networks

    - name: Remove default network from autostart
      virt_net:
        autostart: no
        name: default
      tags: destroy_networks

    - name: Delete iptables rules
      command: iptables -D "{{ item }}"
      with_items:
        - FORWARD -i tun+ -j ACCEPT
        - FORWARD -i tun+ -o team_br+ -m state --state RELATED,ESTABLISHED -j ACCEPT
        - FORWARD -i team_br+ -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
        - OUTPUT -o tun+ -j ACCEPT

    - name: Stop containers
      docker_compose:
        project_src: /home/{{ user }}/ad-infrastructure/
        state: absent
      tags: stop_containers

    - name: Stop terraform
      terraform:
        project_path: /home/{{ user }}/ad-infrastructure/terraform/
        state: absent
      tags: stop_terraform

    - name: Uninstall docker
      apt:
        name: "{{ docker_packages }}"
        state: absent
      tags: uninstall_docker

    - name: Delete ad-infrastructure repository
      file:
        path: /home/{{ user }}/ad-infrastructure
        state: absent
      tags: delete_ad-infrastructure

    - name: Delete all packages
      apt:
        name: "{{ packages }}"
        state: absent
      tags: delete_packages

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      tags: clean_cache

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      tags: clean_cache
