- name: Deploy all infrastructure on monitoring_server
  hosts: monitoring_server
  gather_facts: true
  become: true

  roles:
    - docker

  tasks:
    - name: Include vars from server_vars.yml file
      include_vars: ./vars/server_vars.yml
      tags:
        include_vars

    - name: Check virtualization enabled
      shell: egrep -c '(vmx|svm)' /proc/cpuinfo
      register: virtualization_check

    - name: Number of processors that supports virtualization is
      debug:
        msg: "{{ virtualization_check.stdout }}"

    - name: Install KVM and libvirt
      apt:
        name: ['cpu-checker', 'qemu-kvm', 'libvirt-daemon-system', 'libvirt-clients', 'bridge-utils']
        state: present
        update_cache: yes
      when: virtualization_check.stdout | int > 0

    - name: Add username to libvirt and kvm groups
      command: sudo adduser {{ user }} {{ item }}
      loop:
        - libvirt
        - kvm

    - name: Check status of libvirtd and(or) enable it
      systemd:
        name: libvirtd
        state: started
        enabled: yes

    - name: Install terraform dependencies
      apt:
        update_cache: yes
        name: ['gnupg', 'software-properties-common', 'curl']

    - name: Add the HashiCorp GPG key.
      shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

    - name: Add the official HashiCorp Linux repository.
      shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

    - name: Install terraform
      apt:
        update_cache: yes
        name: terraform

    - name: Create ad-infrastructure dir on monitoring_server
      file:
        path: ~/ad-infrastructure
        state: directory
        mode: '0755'

    - name: Upload necessary directories to monitoring_server
      copy:
        src: ../{{ item }}
        dest: /home/{{ user }}/ad-infrastructure/
      with_items:
        - ansible
        - ad-infrastructure-api
        - ovpn-admin
        - monitoring
        - tasks
        - terraform
        - user_rsa
        - docker-compose.yml
        - .env
        - network.xml.j2
        - test.json
      tags:
        - upload_files

    - name: Check that iso_image exists
      stat:
        path: /home/{{ user }}/ad-infrastructure/{{ iso_image }}
      register: image_check

    - name: Download .iso image if it doesn`t exists
      get_url:
        url:  '{{ wget_image }}'
        dest: /home/{{ user }}/ad-infrastructure/
      when: not image_check.stat.exists


    - name: Resize .iso image
      command: chdir=/home/{{ user }}/ad-infrastructure sudo qemu-img resize {{ iso_image }} {{ image_size }}


    - name: Add system environment variables
      lineinfile:
        path: /home/{{ user }}/.bashrc
        line: "export {{ item.varname }}={{ item.varvalue }}"
      loop:
        - { varname: 'SERVER_IP', varvalue: '{{ server_ip }}' }
        - { varname: 'ADMIN_PASS', varvalue: '{{ admin_pass }}' }
      tags:
        - set_env_vars

    - name: OpenDistro max_map_count user }}
      sysctl:
        name: vm.max_map_count
        value: 262144

    - name: Stop current containers
      docker_compose:
        project_src: /home/{{ user }}/ad-infrastructure/
        state: absent
      tags:
        - stop_containers

    - name: Run api
      docker_compose:
        project_src: /home/{{ user }}/ad-infrastructure/
        build: yes
        services:
          - mongo
          - redis
          - openvpn
          - ovpn-admin
        debug: yes
      tags:
        - deploy_api

    - name: Run ad-api
      docker_compose:
        project_src: /home/{{ user }}/ad-infrastructure/
        build: yes
        services:
          - ad-api
        debug: yes
      tags:
        - deploy_api

    - name: Run monitoring
      docker_compose:
        project_src: /home/{{ user }}/ad-infrastructure/
        build: yes
        services:
          - node1
          - node2
          - kibana
          - logstash
        debug: yes
      tags:
        - deploy_monitoring


    - name: Pause playbook to create networks
      pause:
        prompt: Please confirm you configure networks and ready to resume playbook

    - name: Define JSON response
      uri:
        url: "http://192.168.100.116:8000/api/v1/services/teams/info"
        method: GET
        headers:
          Content-Type: "application/json"
      ignore_errors: true
      register: result
      tags: get_result

    - name: Define networks
      virt_net:
        command: define
        name: "{{ item['name'] }}"
        xml: "{{ lookup('template', 'network.xml.j2') }}"
      with_items: "{{ result.json.teams }}"
      tags: define_networks

    - name: Setting state of virtual networks
      virt_net:
        name: "{{ item['name'] }}"
        state: active
      with_items: "{{ result.json.teams }}"

    - name: Setting virtual networks to autostart
      virt_net:
        autostart: true
        name: "{{ item['name'] }}"
      with_items: "{{ result.json.teams }}"

    - name: Build and run vm`s with terraform
      terraform:
        project_path: /home/{{ user }}/ad-infrastructure/
        state: present
        force_init: true
      tags:
        - terraform_deploy
