- name: Auditbeat, packetbeat, docker installation and configuration
  hosts: # host from ad_hosts.ini
  gather_facts: true
  serial: 1
  become: true

  roles:
    - docker
    - auditbeat
    - packetbeat
