- name: Download and install the Public Signing Key(PacketBeat)
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Install https
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: Save the repository definition to /etc/apt/sources.list.d/elastic-7.x.list
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Install Auditbeat
  apt:
    name: "packetbeat"
    state: present
    update_cache: yes

- name: Check auditbeat service status
  systemd:
    state: started
    name: packetbeat

- name: Enable auditbeat service
  systemd:
    name: packetbeat
    enabled: yes

- name: Replace packetbeat.yml with custom
  ansible.builtin.copy:
    src: ../packetbeat.yml
    dest: /etc/packetbeat/packetbeat.yml
    mode: '664'
